In [1]:
import numpy as np
array = np.array([4,9,16,25])
type(array)

numpy.ndarray

In [2]:
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']


In [4]:
import numpy as np
a = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])

In [13]:
a[2,1]

1

In [10]:
sample_array = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
sample_array[[0,4,7]]

array([10, 14, 17])

In [ ]:
sample_array = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
sample_array[0:4]

array([10, 11, 12, 13])

In [15]:
a = np.array([[1,0,1,0,2,3], [1,3,0,1,2,0], [0,1,0,0,1,3]])
b = a[:,1:3]
print(b)

[[0 1]
 [3 0]
 [1 0]]


In [16]:
array1 = np.array([[0,3,2,5],[1,0,2,-2]])
print(array1 >= 3)

[[False  True False  True]
 [False False False False]]


In [17]:
array2 = np.array([[1,3,5],[2,4,6]])
print((array2*2)**2)

[[  4  36 100]
 [ 16  64 144]]


In [18]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b
a + 5

array([5, 6, 7])

In [19]:
a=np.arange(10)
b=np.power(a,2)
b.max()

81

In [20]:
print((2**3)//5)

1


In [21]:
print(27/2==13.5, 27%2!=1, 27//2==13)

True False True


In [22]:
i=8

i=+2

print(i)

2


In [23]:
number=[0,1,2,3,4,5]

print( number[2:3] + number[1:3] + number[0:6:2])

[2, 1, 2, 0, 2, 4]


In [29]:
course=['ML', 'Data Science', 'AI', 'Python']

course.insert(1, 'Deep Learning')

del course[2]

course.remove('Python')

course = course*2
print(course)

['ML', 'Deep Learning', 'AI', 'ML', 'Deep Learning', 'AI']


In [35]:
number=[1, 2, 2, 3, 2, 3, 1, 3]

s=set(number)

number=list(s)

print(number)

[1, 2, 3]


In [36]:
if 4+5==9:
    print("nine")
if 5+5==9:
    print("nine")
else:
    print("ten")
print("ten")

nine
ten
ten


In [37]:
l=[2,3,5,6,9]
for i in l:
    print(i**2)

4
9
25
36
81


In [39]:
l=["Great Learning", "Data Science", "Machine Learning", "AI"]
for i in l:
    print(i[1])

r
a
a
I


In [40]:
i=0

while i<=5:

       print(i)

       i+=1

0
1
2
3
4
5


In [41]:
i=0

while i<5:

       print(i)

       i+=1

0
1
2
3
4


In [45]:
i=0

while i<5:

       i+=1

       print(i+1)

2
3
4
5
6


In [46]:
i=0

while i<4:

       print(i+1)

       i+=1

1
2
3
4


In [47]:
def square(n):
    return n*n

In [48]:
square(2)

4

In [49]:
def addition(a, b):
    print(a+b)

In [52]:
addition(a,b)

[ 0  2  6 12 20 30 42 56 72 90]


In [53]:
def search(seq):
    for i in seq:
        if i==8:
            return 8
        else:
            print(i)

In [54]:
seq=[2, 7, 1, 8, 1, 4]
n=search(seq)

2
7
1


In [55]:
def add(a,b,c):

       sum=0

       sum=a+b+c

       return sum

sum=add(1,2,3)

In [61]:
def add(**kwargs):
           sum=0

           for i in kwargs:

        sum+=i

    return sum

sum=add(1,2,3)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 6)

In [59]:
def add(*args):

          sum=0

           for i in args:

                  sum+=i

            return sum

sum=add(1,2,3)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [62]:
def add(l):

           sum=0

           for i in l:

                  sum+=i

           return sum

l=[1,2,3]

sum=add(l)

In [63]:
def add():

           sum=0

           l=[1,2,3]

           for i in l:

                  sum+=i

           return sum

add()

6

In [64]:
def func(num1):
    print(num1)

In [65]:
num2=20
func(num2)

20


In [66]:
def odd(n):
    print("The number is odd")

In [67]:
def even(n):
    print("The number is even")

In [68]:
for i in range(11):
    if i%2==0:
        even(i)
    else:
        odd(i)

The number is even
The number is odd
The number is even
The number is odd
The number is even
The number is odd
The number is even
The number is odd
The number is even
The number is odd
The number is even


In [69]:
def cube(n):
    return n**3

In [70]:
for i in range(0,10):
    c=cube(i)
    print(c)

0
1
8
27
64
125
216
343
512
729


In [71]:
def cube(n):
    if n==10:
        return 1
    print(n**3)
    cube(n+1)
cube(0)

0
1
8
27
64
125
216
343
512
729


In [72]:
names1 = ['Mike', 'Barry', 'Charles', 'Dao']
names2 = [name.lower() for name in names1]
print (names2[2][0])

c


In [73]:
num1=[1,2,4,6,9]
num2=num1*int(1.5*2)
num3=str(num2)
num3[4]

'2'

In [74]:
isinstance((1,),tuple)

True

In [75]:
all([1.,4,2,'False'])

True

In [76]:
any([0,''])

False

In [77]:
bool('0')

True

In [78]:
x = True
y = False
z = False 
if not x or y: 
        print (1) 
elif not x or not y and z: 
        print (2) 
elif not x or y or not y and x: 
        print (3)
else:
         print (4)

3


In [87]:
for i in [1,2,3,4,5]:
 if i//2==1 | i==4:
    print(i)
 else:
    break
 return i

SyntaxError: 'return' outside function (2064532960.py, line 6)

In [91]:
def display(**kwargs):
    for i in kwargs:
        print(i)

display(emp="King", salary=100000)

emp
salary


In [92]:
def fun(a,*b):

    print(a+len(b))

fun(3,8,9,"t",4.0)

7


In [93]:
numbs=[1, 4, 7, 9, 1, 5]
print(len(numbs), numbs.count(1), numbs.index(9), numbs.pop())

6 2 3 5


In [97]:
def func(v1,v2,v3):

    print(v1+v2+v3)

In [99]:
func('apple',v2='mango','lemon')

SyntaxError: positional argument follows keyword argument (135985112.py, line 1)

In [100]:
l=['T', 'F']
for i in l:
     for j in l:
          print(i+j)

TT
TF
FT
FF


In [102]:
numb_list=[1, 3, 2, 8, 0, 9]
numb_tuple=(2, 4, 7, 1)
numb_dictionary={'first': 1, 'second': 2, 'third':3}
numb_set={numb_list[0], numb_tuple[-1], numb_dictionary['first']}
print(numb_set)

{1}


In [6]:
i=0
while i<5:
 print(i)
 i+=1
        



0
1
2
3
4


In [13]:
def age_comp(missing_value_1):
     if age<18:
            print('Child')
        elif: age>=18 and age<65:
            print('Adult')
else:
          print('Senior)

*missing_value_3*

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 4)

In [17]:
x=3.0
if type(x)==int:
     print('int')
elif type(x)==float:
     print('float')
else:
     print('string')

float


In [19]:
num=8
for i in range(5):
    print(num/i)

ZeroDivisionError: division by zero

In [20]:
num=2
cube=(num**3)/2
print(cube, type(cube))

4.0 <class 'float'>


In [21]:
x=5
if x>=5 and x<1:
     print(1)
elif x<=4 or x>3:
     print(2)
else:
     print(3)

2


In [23]:
import pandas as pd
 

In [25]:
data = [0.85, 0.8, 0.98, 0.74, 0.4, 0.55, 0.94, 0.42, 0.43, 0.92]


In [28]:
ser = pd.Series(data=data)
ser.sort_values(ascending=False)

2    0.98
6    0.94
9    0.92
0    0.85
1    0.80
3    0.74
5    0.55
8    0.43
7    0.42
4    0.40
dtype: float64

In [27]:
print(ser)

0    0.85
1    0.80
2    0.98
3    0.74
4    0.40
5    0.55
6    0.94
7    0.42
8    0.43
9    0.92
dtype: float64


In [29]:
data = range(10)
new_ser = pd.Series(data = data)
new_ser[new_ser == 5]

5    5
dtype: int64

In [30]:
a1 = ['Hogwarts', 'Durmstrang', 'Beauxbatons']
a2 = ['Hogwarts', 'Durmstrang', 'Beauxbatons']
a3 = ['Hogwarts', 'Durmstrang', 'Beauxbatons']
school = [a1, a2, a3]
inst = ['School_1', 'School_2', 'School_3']
Muggle_data = pd.DataFrame(data = school, columns = inst)

In [31]:
print(Muggle_data)

   School_1    School_2     School_3
0  Hogwarts  Durmstrang  Beauxbatons
1  Hogwarts  Durmstrang  Beauxbatons
2  Hogwarts  Durmstrang  Beauxbatons


In [33]:
data = {'A':[1,2,3,4,5], 'B':[1,0,1,1,0]}

In [34]:
df = pd.DataFrame(data = data)
df.C = df.A + df.B

C:\Users\joshu\AppData\Local\Temp\ipykernel_36916\1181864398.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.C = df.A + df.B


In [35]:
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data

day  calories  duration_min
0  day1       450            30
1  day2       300            25
2  day3       345            29
3  day4       520            39
4  day5       600            48

In [36]:
calorie_data.loc[[1,2],['calories']]

calories
1       300
2       345

In [37]:
calorie_data.iloc[[1,2],[1]]

calories
1       300
2       345

In [38]:
import pandas as pd
import numpy as np
ser1 = pd.Series(list('abcd'))
ser2 = pd.Series(np.arange(4))

In [40]:
df = pd.concat([ser1, ser2], axis = 1)
print(df)

   0  1
0  a  0
1  b  1
2  c  2
3  d  3


In [41]:
df = pd.DataFrame({'col1': ser1, 'col2': ser2})

In [42]:
print(df)

  col1  col2
0    a     0
1    b     1
2    c     2
3    d     3


In [43]:
df = pd.concat([ser1, ser2], axis = 0)

In [44]:
print(df)

0    a
1    b
2    c
3    d
0    0
1    1
2    2
3    3
dtype: object


In [45]:
data1 = {'Physics': [77, 75, 100, 10, 59], 'Chemistry': [85, 70, 99, 30, 80]}
df1 = pd.DataFrame(data = data1)
data2 = {'Student_ID': [0, 1, 2, 3, 4], 'Maths': [80, 90, 88, 25, 90]}
df2 = pd.DataFrame(data=data2)
df3 = pd.concat([df1, df2], join = 'inner', axis = 0, ignore_index = True)

In [46]:
print(df3)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [47]:
data1 = {'Student_ID': [3, 4, 6, 8, 10], 'CGPA': [4.5, 3, 4.37, 3.5, 4]}
df1 = pd.DataFrame(data = data1)
data2 = {'Student_ID': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
'Maths': [4,52, 5, 2.5, 3, 3.9, 2.8, 4.75, 3.68, 5, 4.8]}
df2 = pd.DataFrame(data = data2)
df3 = pd.merge(df2, df1, on = 'Student_ID', how = 'left') 

In [48]:
print(df3)

    Student_ID  Maths  CGPA
0            0   4.00   NaN
1            1  52.00   NaN
2            2   5.00   NaN
3            3   2.50  4.50
4            4   3.00  3.00
5            5   3.90   NaN
6            6   2.80  4.37
7            7   4.75   NaN
8            8   3.68  3.50
9            9   5.00   NaN
10          10   4.80  4.00


In [49]:
header = pd.MultiIndex.from_product([['Before Course','After Course'],['Marks']])
d = ([[82,95],[78,89]])
 
my_df = pd.DataFrame(d,
 index = ['Alisa','Bobby'],
 columns = header)

print(my_df.stack(level = 0).unstack(level = 0))

              Marks      
              Alisa Bobby
After Course     95    89
Before Course    82    78


In [50]:
df = pd.DataFrame({"Gender": ["Male", "Male", "Female", "Female", "Female", "Female", "Male", "Male", "Female"],
 "Movie_Genre": ["Action", "Comedy", "Drama", "Action", "Comedy", "Drama", "Action", "Drama", "Action"],
 "Rating": [1, 5, 3, 2, 3, 4, 4, 5, 4]})

In [51]:
pd.pivot_table(data=df, index='Gender', values='Rating', aggfunc='mean')

Rating
Gender        
Female    3.20
Male      3.75

In [53]:
pd.pivot_table(data=df, index='Gender')

Rating
Gender        
Female    3.20
Male      3.75

In [54]:
pd.pivot_table(data=df, index='Gender', values='Rating')

Rating
Gender        
Female    3.20
Male      3.75

In [56]:
pd.pivot_table(data=df, index='Rating', values='Gender', aggfunc='mean')

C:\Users\joshu\AppData\Local\Temp\ipykernel_36916\3155889201.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.mean is deprecated. In a future version, a TypeError will be raised. Before calling .mean, select only columns which should be valid for the function.
  pd.pivot_table(data=df, index='Rating', values='Gender', aggfunc='mean')


Empty DataFrame
Columns: []
Index: [1, 2, 3, 4, 5]

In [57]:
pd.pivot_table(data=df, index='Gender', 'Movie_Genre' , values='Rating', aggfunc='sum')

SyntaxError: positional argument follows keyword argument (4099935273.py, line 1)

In [59]:
pd.pivot_table(data=df, index=['Gender', 'Movie_Genre'] , values='Rating', aggfunc='sum')

Rating
Gender Movie_Genre        
Female Action            6
       Comedy            3
       Drama             7
Male   Action            5
       Comedy            5
       Drama             5

In [60]:
pd.pivot_table(data=df, index=['Gender', 'Movie_Genre'] , values='Rating', aggfunc='sum')

Rating
Gender Movie_Genre        
Female Action            6
       Comedy            3
       Drama             7
Male   Action            5
       Comedy            5
       Drama             5

In [61]:
df_employee = [('John', 3400, 'Sydeny'),
 ('Robert', 3000, 'Chicago'),
 ('Aadi', 1600, 'New York'),
 ('Robert', 3000, 'Chicago'),
 ('Robert', 3000, 'Chicago'),
 ('Robert', 3000, 'Texas'),
 ('Aadi', 4000, 'London'),
 ('Sachin', 3000, 'Chicago')]
df_employee = pd.DataFrame(df_employee, columns = ['Name', 'Salary', 'City'])
df_employee[df_employee.duplicated('Name')].shape

(4, 3)

NameError: name 'duplicated' is not defined